language: ruby
rvm:
- 2.2
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: "./deploy.sh"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="centaurialpha/pireal"
  - secure: k7Tddqkei1hEntUJffvgcUEoApHcBqMHfDSReFUWopT6iWwVn4w8CturKkImq4HEybCb01ToHpXFgNvViXa0c8RMaftpsBWH5DK2Y7ACQETNcf6UHnCrzROwT60jZjHGbF9AfE/gUVzH7HzDfdCsgy2RW09LxwVN5s7BiCrA/4ThbueN5NrcjF1us9S56z5q7yZ6Wighr7xoXhuppUZCSuq2oQZp1pucS9eXRW5yL+77k7LbKkUPFMUGTqvJ3kG+tGb0RIo+MWOdauAqsbgiMTpmaLwjCeX3THzyAJTC2Pp2iiLAnGcqeiyhdEa3/KS8HmSENqNwHXCOmhUZVnKn//WopZbuRuOya7ecOOjls5a/1qtnfBWnhtLGIDRRjecNdbeaw1K4PiuyZrsICIh0eQ2X4KzqbemDEazpThOZ4PSdxS2F+GXxs8tAIOfqqFWH3eGqYpF4Z79Beu5WLVvp0eVxPWV6RFw4PzwtKS3VLEY39XYq86m4M9xEwKvQOtrMa5SdYLO7ZIRUN1ZgenjMty7F81IMPlVTOmd8PsS+Zn89cj/E6tqSTGE4RUlVRd9CTa4Eo4Me80tYTaah0ZCxbsESx9iz42H2q2dIdvR3/DzZEwGqn73T/fQxo4QAGGojUM65TSytf3+YYOXX3EPIRdOLgJ9SJePEhoICwK0CXfU=
branches:
  only:
  - gh-pages
  - source
notifications:
  email: false
